#ifndef MAIN_APP_HANDLER_ZIGBEE_FZ_HANDLER_ZIGBEE_FZ_HANDLER
#define MAIN_APP_HANDLER_ZIGBEE_FZ_HANDLER_ZIGBEE_FZ_HANDLER

#include <stdbool.h>

bool zigbee_fz_handler_init(void);

#endif /* MAIN_APP_HANDLER_ZIGBEE_FZ_HANDLER_ZIGBEE_FZ_HANDLER */
