#ifndef MAIN_APP_HANDLER_RESET_BUTTON_HANDLER_RESET_BUTTON_HANDLER
#define MAIN_APP_HANDLER_RESET_BUTTON_HANDLER_RESET_BUTTON_HANDLER

#include <stdbool.h>

bool reset_button_handler_init(void);

#endif /* MAIN_APP_HANDLER_RESET_BUTTON_HANDLER_RESET_BUTTON_HANDLER */
